In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
x1 = tf.constant([1,0,3,0,5], tf.float32) # 공부한시간
x2 = tf.constant([0,2,3,4,5], tf.float32) # 출석일수
y = tf.constant([1,2,3,4,5], tf.float32) # 받은점수

In [3]:
w1 = tf.Variable(tf.random_uniform([1]))
w2 = tf.Variable(tf.random_uniform([1]))
b = tf.Variable(tf.random_uniform([1]))

In [4]:
hx = w1*x1 + w2*x2 + b
cost = tf.reduce_mean(tf.square(hx-y))

In [5]:
optimizer = tf.train.GradientDescentOptimizer(0.1) #learning rate
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [13]:
# train학습
for i in range(100):
    sess.run(train)
    print(i,sess.run(cost))

0 0.40061846
1 0.3982718
2 0.39594242
3 0.3936302
4 0.39133507
5 0.38905674
6 0.38679525
7 0.3845504
8 0.38232192
9 0.38010997
10 0.37791434
11 0.37573487
12 0.37357125
13 0.3714236
14 0.3692917
15 0.36717555
16 0.3650749
17 0.36298975
18 0.36091977
19 0.3588651
20 0.35682547
21 0.35480088
22 0.3527911
23 0.35079604
24 0.34881562
25 0.3468497
26 0.34489837
27 0.34296122
28 0.34103826
29 0.33912945
30 0.33723462
31 0.3353536
32 0.3334864
33 0.33163303
34 0.329793
35 0.32796654
36 0.32615355
37 0.32435375
38 0.32256716
39 0.3207937
40 0.3190331
41 0.3172854
42 0.31555048
43 0.31382838
44 0.3121187
45 0.31042153
46 0.30873695
47 0.3070645
48 0.30540437
49 0.30375633
50 0.3021204
51 0.3004964
52 0.2988842
53 0.29728377
54 0.29569513
55 0.29411793
56 0.29255235
57 0.29099813
58 0.28945524
59 0.28792372
60 0.28640324
61 0.28489393
62 0.2833956
63 0.2819082
64 0.28043163
65 0.2789658
66 0.2775106
67 0.27606612
68 0.27463213
69 0.27320856
70 0.27179536
71 0.27039236
72 0.26899973
73 0.2676171


In [10]:
sess.run(w1)

array([0.3895349], dtype=float32)

In [11]:
sess.run(w2)

array([0.6590111], dtype=float32)

In [12]:
sess.run(b)

array([0.2231976], dtype=float32)