In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn import preprocessing # 전처리

In [2]:
data = [[828, 920, 1234567, 1020, 1111],

            [824, 910, 2345612, 1090, 1234],

            [880, 900, 3456123, 1010, 1000],

            [870, 990, 2312123, 1001, 1122],

            [860, 980, 3223123, 1008, 1133],

            [850, 970, 2432123, 1100, 1221]]

data = np.float32(data)

In [3]:
# data[:, :-1]  : 0<=col<-1 
xdata = data[:,:-1]
ydata = data[:,[-1]]

In [4]:
xdata

array([[8.280000e+02, 9.200000e+02, 1.234567e+06, 1.020000e+03],
       [8.240000e+02, 9.100000e+02, 2.345612e+06, 1.090000e+03],
       [8.800000e+02, 9.000000e+02, 3.456123e+06, 1.010000e+03],
       [8.700000e+02, 9.900000e+02, 2.312123e+06, 1.001000e+03],
       [8.600000e+02, 9.800000e+02, 3.223123e+06, 1.008000e+03],
       [8.500000e+02, 9.700000e+02, 2.432123e+06, 1.100000e+03]],
      dtype=float32)

In [5]:
ydata

array([[1111.],
       [1234.],
       [1000.],
       [1122.],
       [1133.],
       [1221.]], dtype=float32)

In [6]:
x = tf.placeholder(tf.float32, shape=[None,4])
y = tf.constant(ydata, tf.float32)

w = tf.Variable(tf.random_uniform([4,1]))
b = tf.Variable(tf.random_uniform([1]))

hx = tf.matmul(x,w) +b
cost = tf.reduce_mean( tf.square(hx-y) )

optimizer = tf.train.GradientDescentOptimizer( 0.01 )
train = optimizer.minimize( cost )
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [7]:
# 최저점을 찾지 못하기 때문에 학습이 되지 않는다.
for i in range(10000):
    sess.run(train, {x:xdata})
    print(i,sess.run(cost, {x:xdata}))

0 6.794793e+34
1 inf
2 inf
3 inf
4 nan
5 nan
6 nan
7 nan
8 nan
9 nan
10 nan
11 nan
12 nan
13 nan
14 nan
15 nan
16 nan
17 nan
18 nan
19 nan
20 nan
21 nan
22 nan
23 nan
24 nan
25 nan
26 nan
27 nan
28 nan
29 nan
30 nan
31 nan
32 nan
33 nan
34 nan
35 nan
36 nan
37 nan
38 nan
39 nan
40 nan
41 nan
42 nan
43 nan
44 nan
45 nan
46 nan
47 nan
48 nan
49 nan
50 nan
51 nan
52 nan
53 nan
54 nan
55 nan
56 nan
57 nan
58 nan
59 nan
60 nan
61 nan
62 nan
63 nan
64 nan
65 nan
66 nan
67 nan
68 nan
69 nan
70 nan
71 nan
72 nan
73 nan
74 nan
75 nan
76 nan
77 nan
78 nan
79 nan
80 nan
81 nan
82 nan
83 nan
84 nan
85 nan
86 nan
87 nan
88 nan
89 nan
90 nan
91 nan
92 nan
93 nan
94 nan
95 nan
96 nan
97 nan
98 nan
99 nan
100 nan
101 nan
102 nan
103 nan
104 nan
105 nan
106 nan
107 nan
108 nan
109 nan
110 nan
111 nan
112 nan
113 nan
114 nan
115 nan
116 nan
117 nan
118 nan
119 nan
120 nan
121 nan
122 nan
123 nan
124 nan
125 nan
126 nan
127 nan
128 nan
129 nan
130 nan
131 nan
132 nan
133 nan
134 nan
135 nan
136 nan
137 n

### 학습이 되지 않을때 해결 방법
###### 1. learning rate 설정을 아주작게한다.
###### 2. optimizer Adam
###### 3. normalize (정규화)

In [8]:
scale = preprocessing.MinMaxScaler()
dataN = scale.fit_transform(data)

In [9]:
dataN

array([[0.0714283 , 0.22222233, 0.        , 0.19191933, 0.47435904],
       [0.        , 0.11111164, 0.50012016, 0.89899063, 1.0000005 ],
       [1.        , 0.        , 1.        , 0.09090996, 0.        ],
       [0.8214283 , 1.        , 0.48504567, 0.        , 0.52136755],
       [0.6428566 , 0.8888893 , 0.8951186 , 0.07070732, 0.56837654],
       [0.4642849 , 0.7777777 , 0.5390618 , 1.        , 0.94444466]],
      dtype=float32)

In [10]:
xdata = dataN[:,:-1]
ydata = dataN[:,[-1]]

In [11]:
x = tf.placeholder(tf.float32, shape=[None,4])
y = tf.constant(ydata, tf.float32)

w = tf.Variable(tf.random_uniform([4,1]))
b = tf.Variable(tf.random_uniform([1]))

hx = tf.matmul(x,w) +b
cost = tf.reduce_mean( tf.square(hx-y) )

optimizer = tf.train.GradientDescentOptimizer( 0.01 )
train = optimizer.minimize( cost )
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
for i in range(10000):
    sess.run(train, {x:xdata})
    print(i,sess.run(cost, {x:xdata}))

0 0.4916663
1 0.46363214
2 0.43774566
3 0.41383514
4 0.39174306
5 0.3713243
6 0.3524455
7 0.33498397
8 0.31882682
9 0.30387032
10 0.29001892
11 0.2771849
12 0.26528734
13 0.2542521
14 0.24401079
15 0.23450051
16 0.22566354
17 0.21744664
18 0.2098009
19 0.20268132
20 0.19604652
21 0.18985842
22 0.18408196
23 0.17868496
24 0.1736378
25 0.16891314
26 0.16448596
27 0.16033314
28 0.15643343
29 0.15276736
30 0.14931685
31 0.14606543
32 0.14299786
33 0.14010017
34 0.13735941
35 0.13476375
36 0.13230227
37 0.12996496
38 0.1277425
39 0.12562643
40 0.12360892
41 0.12168274
42 0.119841225
43 0.118078314
44 0.11638836
45 0.11476613
46 0.113206886
47 0.11170626
48 0.11026015
49 0.10886485
50 0.10751691
51 0.10621316
52 0.10495069
53 0.1037268
54 0.102538995
55 0.10138502
56 0.10026273
57 0.09917017
58 0.09810556
59 0.09706724
60 0.09605366
61 0.09506344
62 0.09409524
63 0.093147874
64 0.092220224
65 0.091311224
66 0.09041998
67 0.08954555
68 0.08868715
69 0.08784399
70 0.08701539
71 0.08620072
72 0

In [12]:
sess.run(b)

array([0.3820928], dtype=float32)

### 역정규화
#### 정규화를 이용해 값이 나온 데이터를 다시 원상복구
##### [828, 920, 1234567, 1020] 이용하여 학습

In [13]:
# sess.run(hx, {x:[[828, 920, 1234567, 1020, 1111]]}) 정규화가 진행되었기 때문에 이런식으로 주면 안된다
arr = scale.transform([[828, 920, 1234567, 1020, None]])
arr[:,:-1]

array([[7.14281425e-02, 2.22222470e-01, 1.00739044e-08, 1.91919606e-01]])

#### 방법1

In [14]:
sess.run(hx, {x:arr[:,:-1]})

array([[0.5254423]], dtype=float32)

In [15]:
f= scale.inverse_transform([[None,None,None,None,0.5259017]])

In [16]:
f

array([[          nan,           nan,           nan,           nan,
        1123.06093855]])

In [17]:
f[:,-1]

array([1123.06093855])

#### 방법2

In [18]:
labelScale = preprocessing.MinMaxScaler()
y1 = labelScale.fit_transform(data[:,[-1]])

In [19]:
y1

array([[0.47435904],
       [1.0000005 ],
       [0.        ],
       [0.52136755],
       [0.56837654],
       [0.94444466]], dtype=float32)

In [20]:
aa = sess.run(hx, {x:arr[:,:-1]})

In [21]:
aa

array([[0.5254423]], dtype=float32)

In [22]:
labelScale.inverse_transform(aa)

array([[1122.9534]], dtype=float32)