In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# 공부한시간, 출석일수
xdata = [[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]]
ydata = [[0],[0],[0],[1],[1],[1]] # 0 : 불합격 / 1 : 합격

In [3]:
x = tf.placeholder(tf.float32, shape=[None,2])
y = tf.constant(ydata, tf.float32)

In [4]:
w = tf.Variable(tf.random_uniform([2,1]))
b = tf.Variable(tf.random_uniform([1]))

In [5]:
z = tf.matmul(x,w)+b
hx = tf.nn.sigmoid(z)

In [6]:
cost_i = tf.nn.sigmoid_cross_entropy_with_logits(logits=z, logits=y)
# y*(-tf.log(hx))+(1-y)*(-tf.log(1-hx))
cost = tf.reduce_mean(cost_i)

SyntaxError: keyword argument repeated (<ipython-input-6-069513b3c412>, line 1)

In [8]:
optimizer = tf.train.AdamOptimizer( 0.1 )
train = optimizer.minimize( cost )
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [9]:
for i in range(1000):
    sess.run(train,{x:xdata})
    print(i,sess.run(cost, {x:xdata}))

0 1.4254317
1 1.2004328
2 0.9944325
3 0.8248934
4 0.7238721
5 0.72464275
6 0.8005128
7 0.8634133
8 0.8682243
9 0.8228156
10 0.7527115
11 0.68400544
12 0.6350559
13 0.61159474
14 0.6079412
15 0.6135563
16 0.619095
17 0.61877877
18 0.6102423
19 0.59364426
20 0.5708479
21 0.5447982
22 0.5189771
23 0.49677145
24 0.48064435
25 0.47123787
26 0.46688285
27 0.4641209
28 0.4592706
29 0.45016184
30 0.43693933
31 0.42157766
32 0.40661287
33 0.39392138
34 0.38413337
35 0.37675855
36 0.37071028
37 0.36485314
38 0.35836568
39 0.35088718
40 0.3424983
41 0.33360234
42 0.32475492
43 0.31648222
44 0.3091248
45 0.30274484
46 0.29712835
47 0.29188612
48 0.28661692
49 0.281061
50 0.27517644
51 0.26911306
52 0.2631123
53 0.25739297
54 0.25207496
55 0.24716014
56 0.24256156
57 0.23815334
58 0.23381978
59 0.22948706
60 0.2251345
61 0.22078796
62 0.21650107
63 0.21233298
64 0.20832862
65 0.20450617
66 0.20085548
67 0.19734491
68 0.19393413
69 0.1905881
70 0.18728615
71 0.18402548
72 0.18081702
73 0.17767881
74

In [16]:
sess.run(b)

array([-12.886393], dtype=float32)

In [10]:
sess.run(w)

array([[1.8965282],
       [1.9043573]], dtype=float32)

In [11]:
# 3시간공부하고 5일 출석

In [30]:
sess.run(hx,{x:[[3,5]]})

array([[0.9109248]], dtype=float32)

In [14]:
result = sess.run(hx,{x:[[3,5]]})

In [15]:
result>0.5

array([[ True]])

In [32]:
t = tf.cast(result>0.5,dtype=tf.int32)
sess.run(t)

array([[1]])

In [33]:
sess.run(hx,{x:xdata})

array([[0.00508282],
       [0.00504339],
       [0.00500425],
       [0.9978192 ],
       [0.9978021 ],
       [0.9977849 ]], dtype=float32)

In [22]:
h = sess.run(hx,{x:xdata})

In [23]:
h>0.5

array([[False],
       [False],
       [False],
       [ True],
       [ True],
       [ True]])

In [26]:
ydata

[[0], [0], [0], [1], [1], [1]]

In [28]:
(h>0.5) == ydata

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [29]:
((h>0.5) == ydata).mean() # 정확도 100%

1.0

In [41]:
h

array([[0.00508282],
       [0.00504339],
       [0.00500425],
       [0.9978192 ],
       [0.9978021 ],
       [0.9977849 ]], dtype=float32)

In [42]:
predict = tf.cast(h>0.5, dtype=tf.float32)
sess.run(predict)

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [46]:
predict = tf.cast(h>0.5, dtype=tf.float32)
e = tf.equal(predict,y) # predict == y
m = tf.reduce_mean(tf.cast(e,dtype=tf.float32))
sess.run(m)

1.0

In [47]:
predict = tf.cast(h>0.5, dtype=tf.float32)
m = tf.reduce_mean(tf.cast(tf.equal(predict,y),dtype=tf.float32))
sess.run(m)

1.0

In [48]:
sess.run(predict)

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)