In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt

from sklearn import preprocessing
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam

In [2]:
arr = np.loadtxt('softmax.txt')
arr

array([[1., 2., 1., 0., 0., 1.],
       [1., 3., 2., 0., 0., 1.],
       [1., 3., 4., 0., 0., 1.],
       [1., 5., 5., 0., 1., 0.],
       [1., 7., 5., 0., 1., 0.],
       [1., 2., 5., 0., 1., 0.],
       [1., 6., 6., 1., 0., 0.],
       [1., 7., 7., 1., 0., 0.]])

In [3]:
# feature의 갯수 
xdata = arr[:,1:3]
xdata

array([[2., 1.],
       [3., 2.],
       [3., 4.],
       [5., 5.],
       [7., 5.],
       [2., 5.],
       [6., 6.],
       [7., 7.]])

In [4]:
# 분류의 갯수 
ydata = arr[:,3:]
ydata 

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [5]:
x = tf.placeholder(tf.float32,[None,2])
y = tf.constant(ydata, tf.float32)

In [6]:
w = tf.Variable(tf.random_uniform([2,3]))#[f갯수,분류3]
b = tf.Variable(tf.random_uniform([3]))

In [7]:
z = tf.matmul(x,w) + b
hx = tf.nn.softmax(z) # 예측값 확인용도 , 밑의 함수가 있을경우 굳이 사용할필요없다.
tf.nn.sigmoid_cross_entropy_with_logits() #버그수정도 되어있는 버전. 
# cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits=z,labels=y) # label : 실제값
cost = tf.reduce_mean(cost_i)

In [8]:
optimizer = tf.train.GradientDescentOptimizer(0.1) #learning rate
train = optimizer.minimize(cost)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [9]:
for i in range(1000):
    sess.run(train,{x:xdata})
    print(i,sess.run(cost, {x:xdata}))

0 1.4105413
1 1.2176702
2 1.0968685
3 1.0465481
4 1.0181174
5 1.0009066
6 0.9900749
7 0.9818331
8 0.97513896
9 0.96933043
10 0.9641333
11 0.95934814
12 0.95487213
13 0.950629
14 0.94657326
15 0.9426714
16 0.9389019
17 0.93524754
18 0.93169713
19 0.92824125
20 0.92487276
21 0.9215858
22 0.9183755
23 0.91523755
24 0.9121685
25 0.90916485
26 0.9062234
27 0.90334165
28 0.90051734
29 0.8977474
30 0.89503014
31 0.8923632
32 0.8897445
33 0.88717276
34 0.8846457
35 0.8821616
36 0.8797191
37 0.8773166
38 0.8749528
39 0.8726263
40 0.8703355
41 0.86807954
42 0.8658573
43 0.8636676
44 0.861509
45 0.8593811
46 0.8572823
47 0.85521257
48 0.85317004
49 0.85115445
50 0.8491651
51 0.8472009
52 0.84526134
53 0.8433454
54 0.84145296
55 0.839583
56 0.8377352
57 0.8359084
58 0.8341026
59 0.8323171
60 0.8305515
61 0.8288051
62 0.8270774
63 0.82536817
64 0.82367706
65 0.82200336
66 0.8203468
67 0.81870675
68 0.8170833
69 0.8154758
70 0.81388396
71 0.8123075
72 0.81074613
73 0.80919933
74 0.8076669
75 0.80614

In [10]:
sess.run(w)

array([[ 0.7150606 ,  0.57625705,  0.4293838 ],
       [ 1.443724  ,  0.8185044 , -0.33499324]], dtype=float32)

In [11]:
sess.run(b)

array([-4.0252256,  0.4068739,  5.479943 ], dtype=float32)

In [12]:
sess.run(hx,{x:[[6,6]]})

array([[0.52218723, 0.44853497, 0.02927785]], dtype=float32)

In [13]:
sess.run(z, {x:[[6,6]]}) 

array([[8.927482 , 8.775442 , 6.0462866]], dtype=float32)

In [20]:
h = sess.run(hx,{x:[[6,6]]})
h.argmax(axis=1)

array([0], dtype=int64)

In [21]:
grade = ['A','B','C']
grade[ int(h.argmax(axis=1))]

'A'

In [22]:
# 공부한 시간과 출석일수가 6시간 6시간 / 1시간 1시간일 경우 

sess.run(hx, {x:[[6,6],[1,1]]})
# 윗줄 : 6시간 공부한값

array([[5.2218723e-01, 4.4853497e-01, 2.9277846e-02],
       [5.7331397e-04, 2.2460412e-02, 9.7696632e-01]], dtype=float32)

In [23]:
hh = sess.run(hx, {x:[[6,6],[1,1]]})
hh

array([[5.2218723e-01, 4.4853497e-01, 2.9277846e-02],
       [5.7331397e-04, 2.2460412e-02, 9.7696632e-01]], dtype=float32)

In [24]:
# 0 = A학점 2 =C학점
hh.argmax(axis=1)

array([0, 2], dtype=int64)

In [25]:
# matrix 이기 때문에 argmax를 이용하여 원하는 값을 도출한다.

In [26]:
myarr = np.array([[1,2,3],[3,4,5]])
myarr

array([[1, 2, 3],
       [3, 4, 5]])

In [27]:
myarr.argmax() #[1,2,3,4]

5

In [28]:
myarr.sum()

18

In [29]:
myarr.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [30]:
myarr.argmax(axis=1)

array([2, 2], dtype=int64)